name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # better performance in CI without incremental builds

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install required cargo tools
        run: cargo binstall -y cargo-audit
      - name: check
        run: cargo check
      - name: build
        run: cargo build
      - name: test
        run: cargo test
      - name: check formatting
        run: cargo fmt --all -- --check
      - name: audit
        run: cargo audit
      - name: clippy
        run: cargo clippy

  # simplify GH settings: have one single build to be required
  build-results:
    name: Final Results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: check for failed builds
        run: |
          cat <<EOF | jq -e 'unique | all(. == "success")'
          ${{ toJson(needs.*.result) }}
          EOF
